version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - propertify-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  propertify-data:
